#!/bin/sh /etc/rc.common
# Refresh Prometheus textfile metrics from nodectl once a minute.

START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh -c 'while /usr/libexec/nodectl/textfile; do sleep 60; done'
	procd_set_param respawn 3600 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
